modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "LGPL-3.0-only"

[[mixins]]
config = "doapi.mixins.json"
[[mixins]]
config = "doapi-common.mixins.json"

[[mods]]
modId = "doapi"
version = "1.3.1"
displayName = "[Let's Do] API"
authors = "Cristelknight, BaumeisterJO"
logoFile = "pack.png"
description = '''
This is an API for the Let's do mods
'''

[[mods]]
modId = "terraform"
version = "7.0.1"
displayName = "Terraform Wood Api Reforged"
credits = "Prospector, coderbot16, TerraformersMC, for making the original"
authors = "Cristelknight999"
description = '''
Terraform Wood Api, but for forge
'''

[[dependencies.doapi]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doapi]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doapi]]
modId = "architectury"
type = "required"
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"